# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import esiomotores.contacts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='NOME')),
                ('email', models.EmailField(max_length=60, verbose_name='EMAIL')),
                ('phone', models.CharField(max_length=11, validators=[esiomotores.contacts.validators.validate_phone], verbose_name='TELEFONE')),
                ('msg', models.TextField(max_length=700, verbose_name='MENSAGEM')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='ENDEREÇO IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ENVIADA EM')),
            ],
            options={
                'verbose_name': 'MENSAGEM',
                'verbose_name_plural': 'MENSAGENS',
                'ordering': ('-created_at',),
            },
        ),
    ]
